Manna-voca/zenga-frontend

src/pages/Login.tsx
=> 로그인 페이지 임시 수정

src/components/InputText.tsx, src/pages/OldChannelOnboarding.tsx
=> 인풋 컴포넌트 에러 헬프 메시지 추가

src/components/BlockNumber.tsx, src/components/Header.tsx, src/components/InputProfile.tsx, src/pages/CreateCard.tsx, src/pages/MeetupDetail.tsx
=> Feat: qa에 맞게 수정1

src/components/BtnInfoDuplicate.tsx, src/components/PopupComplaint.tsx, src/components/Toast.tsx
=> 클립보드 토스트창 수정

src/pages/Login.tsx
=> Test: IOS 테스트

src/components/BtnInfoDuplicate.tsx, src/components/PopupComplaint.tsx
=> 클립보드 실패 수정

src/pages/Praise.tsx
=> 클립보드 토스트 모두 적용

src/components/Card.tsx, src/components/ChannelList.tsx, src/components/GatheringList.tsx, src/components/InputProfile.tsx, src/components/ProfileMeetup.tsx, src/components/Sidebar.tsx, src/pages/CreateChannel.tsx, src/pages/MeetupDetail.tsx, src/pages/MeetupHome.tsx, src/pages/ModifyProfileInfo.tsx, src/pages/MyMeetup.tsx, src/pages/NewChannelOnboarding.tsx, src/pages/OldChannelOnboarding.tsx
=> api 연동 및 자잘한 오류 수정

src/components/Sidebar.tsx, src/pages/ChannelHome.tsx, src/pages/MeetupDetail.tsx, src/pages/MeetupHome.tsx, src/pages/MeetupMember.tsx
=> Hotfix: accesstoken 수정

src/App.tsx, src/components/ProfileMeetup.tsx, src/components/ProfileZenga.tsx, src/pages/Login.tsx
=> Feat: api 추가연동

src/App.tsx, src/components/Header.tsx, src/components/ImagePreview.tsx, src/components/MeetupImageEditor.tsx, src/components/SendPraise.tsx, src/components/Timer.tsx, src/components/TokenRefresh.tsx, src/index.tsx, src/pages/ChannelHome.tsx, src/pages/CheckChannelCode.tsx, src/pages/CreateMeetup.tsx, src/pages/EditMeetup.tsx, src/pages/MeetupDetail.tsx, src/pages/MeetupHome.tsx, src/pages/Notification.tsx, src/pages/OldChannelOnboarding.tsx, src/pages/Praise.tsx
모임생성수정 & 리프레쉬 & 링크로 채널 입장
모임생성수정 & 리프레쉬 & 링크로 채널 입장
=> 모임생성수정 & 리프레쉬 & 링크로 채널 입장

src/components/Header.tsx, src/pages/Album.tsx, src/pages/CreateCard.tsx, src/pages/MeetupDetail.tsx, src/pages/MeetupMember.tsx, src/pages/MyMeetup.tsx
=> Feat: api 추가

src/components/ButtonMultiple.tsx, src/pages/Comment.tsx
=> Feat: 댓글 api 연동

src/pages/Comment.tsx
=> Fix: 댓글 데이터 size 지정

src/components/PraiseWrapper.tsx, src/pages/Comment.tsx
페이지 렌더링시에만 fetch point를 했었는데
칭찬을 열고나서도 fetch하여 최신 포인트로 변경
=> Fix: 칭찬 열기 포인트 fetch 추가

src/components/ButtonBasic.tsx, src/components/ChannelList.tsx, src/components/ProfileMeetup.tsx, src/pages/Album.tsx, src/pages/Login.tsx, src/pages/MeetupDetail.tsx
=> Feat: qa 반영

src/components/ChannelList.tsx, src/components/ProfileAlbum.tsx, src/components/ProfileMeetup.tsx, src/components/ProfileUpper.tsx, src/components/Sidebar.tsx, src/pages/Album.tsx, src/pages/MeetupMember.tsx, src/pages/ModifyChannelInfo.tsx, src/pages/MyMeetup.tsx
=> Fix: api, navigate state 오류 수정

src/pages/Album.tsx, src/pages/NewChannelOnboarding.tsx, src/pages/OldChannelOnboarding.tsx
=> Fix: 기본 이미지url 변경

src/pages/Album.tsx, src/pages/CreateCard.tsx
=> Feat: 앨범 저장 기능 완

package-lock.json, package.json, src/App.tsx, src/components/Header.tsx, src/components/Timer.tsx, src/components/TokenRefresh.tsx, src/index.tsx, src/pages/ChannelHome.tsx, src/pages/CheckChannelCode.tsx, src/pages/CreateMeetup.tsx, src/pages/Login.tsx, src/pages/MemberList.tsx, src/pages/NewChannelOnboarding.tsx, src/pages/Notification.tsx
lodash debounce를 이용해 api 중복 호출 방지
#성공적
=> lodash debounce를 이용해 api 중복 호출 방지

src/pages/Album.tsx, src/pages/CreateCard.tsx, src/pages/Login.tsx, src/pages/MeetupDetail.tsx, src/pages/MeetupHome.tsx
=> Fix: 이미지 다운로드

src/components/Timer.tsx
=> 칭찬 타이머 새로고침 수정

src/components/ProfileZenga.tsx, src/pages/Memberpage.tsx, src/pages/Mypage.tsx
=> Fix: 남의 페이지에서 남의 멤버 id로 블럭 API 호출하도록 변경

src/pages/MeetupDetail.tsx
=> Design: 모임 상세 정보에서 icon 및 글자 상하정렬

src/pages/Comment.tsx
댓글 api 변동사항 반영
get comment 시 query string에 채널 id 추가
=> 댓글 api 변동사항 반영

public/favicon/site.webmanifest, public/index.html
=> Fix: 파비콘 설정 오류 1차 수정

src/components/PointList.tsx, src/components/ProfileAlbum.tsx, src/components/ProfileMeetup.tsx, src/pages/Album.tsx, src/pages/CreateCard.tsx, src/pages/Login.tsx, src/pages/MeetupDetail.tsx, src/pages/MyMeetup.tsx
=> Fix: 쿼리스트링 문제, 사진 다운로드 수정

src/pages/Album.tsx, src/pages/CreateCard.tsx, src/pages/MeetupDetail.tsx
=> Fix: 공유 링크 오류 수정 및 사진 다운로드 수정

src/pages/Album.tsx
=> hotfix-카톡인앱브라우저 사진 다운로드 확인

src/pages/Album.tsx
=> hotfix_download

src/components/Card.tsx, src/pages/Album.tsx
=> Design: 앨범 내 텍스트 영역 Dimmed 배경 추가

src/components/SendPraise.tsx
=> Fix: 칭찬 셔플 및 인원 로직 수정

src/pages/MemberList.tsx
=> Fix: 멤버리스트 무한 스크롤 수정

src/components/BtnProfileThumbnail.tsx, src/pages/MeetupDetail.tsx
=> Fix: 닉네임 길이 고려하여 모임 상세 페이지 스타일 수정

src/pages/OldChannelOnboarding.tsx
=> Hotfix: 채널 가입시 로그인 실패 에러 수정

public/index.html
=> Fix: manifest cross origin 추가

public/index.html
=> Fix: maniest 경로 변경
